apiVersion: v1
kind: Service
metadata:
  name: "mylb1"
spec:
  selector:
    app: webserver
  type: NodePort         #By default it takes type= ClusterIP
  ports:
   - targetPort: 80      #port of container service
     port: 8080          #port of lb service
     nodePort: 31000     #NodePort tpo connect t o outer world
