apiVersion: v1
kind: ReplicationController
metadata:
   name: "myrc"
spec:
   selector:
     app:web
   template:
     metadata:
       name: "mypod1"
       labels:
         app:web
     spec:
       containers:
         name: "mycont1"
         image: "vimal13/apache-webserver-php"