apiVersion: v1
kind: ReplicationController
metadata:
  name: "replicationcontroller1"
spec:
  selector:
    app: webserver
  replicas: 3
  template:
    metadata:
      name: "rc1-pod-1"
      labels: 
        app: webserver
        region: india
    spec:
      containers:
       - name: "rc1-p1-c1"
         image: "vimal13/apache-webserver-php"

